version: '3'

volumes:
    vm_postgres: { }

services:
    postgres:
        image: postgres:12.7
        ports:
            - 5432:5432
        volumes:
            - vm_postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: socol
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    postgres-migration:
        network_mode: host
        image: postgres:12.7
        working_dir: /var/lib/postgresql
        volumes:
            - ./migration/pg:/var/lib/postgresql/migration
            - ./migration/migration.sh:/var/lib/postgresql/migration.sh
        environment:
            PGUSER: postgres
            PGHOST: localhost
            PGDATABASE: socol
            PGPASSWORD: password
        entrypoint: [ "bash", "/var/lib/postgresql/migration.sh" ]
#        depends_on:
#            - postgres