version: '3'

volumes:
    vm_postgres: { }
    redis_data: { }

services:
    postgres:
        image: postgres:12.7
        ports:
            - 5432:5432
        volumes:
            - vm_postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: socol
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    postgres-migration:
        network_mode: host
        image: postgres:12.7
        working_dir: /var/lib/postgresql
        volumes:
            - ./migration/pg:/var/lib/postgresql/migration
            - ./migration/migration.sh:/var/lib/postgresql/migration.sh
        environment:
            PGUSER: postgres
            PGHOST: localhost
            PGDATABASE: socol
            PGPASSWORD: password
        entrypoint: [ "bash", "/var/lib/postgresql/migration.sh" ]
#        depends_on:
#            - postgres

    redis-slave-1:
        image: redis:6.2
        ports:
            - 16379:6379
        volumes:
            - ./config/redis-slave.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf

    redis-slave-2:
        image: redis:6.2
        ports:
            - 26379:6379
        volumes:
            - ./config/redis-slave.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
