server:
  port: 8081

spring:
  application:
    name: food-facility
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/socol
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      fail-on-empty-beans: false
app:
  export:
    enable: false
#timeout setting for httpClient
timeout:
  httpClient:
    connectionMillis: 2000
    readMillis: 10000
    wirteMillis: 20000

crossOrigin:
  maxAge: 3600
  origins: "*"
  methods: "GET, PUT, POST, DELETE, OPTIONS"
  headers: "x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN"