create table IF NOT EXISTS mobile_food_facility (
    id serial PRIMARY KEY NOT NULL,
    location_id integer,
    applicant varchar(1024),
    facility_type varchar(64),
    cnn text,
    location_description text,
    address varchar(1024),
    block_lot varchar(1024),
    block varchar(1024),
    lot varchar(1024),
    permit varchar(1024),
    status varchar(1024),
    food_items text,
    x text,
    y text,
    latitude text,
    longitude text,
    schedule text,
    days_hours varchar(64),
    noi_sent varchar(64),
    approved varchar(64),
    received varchar(64),
    prior_permit text,
    expiration_date varchar(64),
    location varchar(512),
    fire_prevention_districts varchar(64),
    police_districts varchar(64),
    supervisor_districts varchar(64),
    zip_codes varchar(64),
    neighborhoods varchar(64)
);